// Generate the shared CP1254 tables from SQL Server captures.
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
const source = JSON.parse(readFileSync(new URL('../corpus/sql2025/turkish-codepage.expected.json', import.meta.url)))
function value(key) {
  const step = source.cases[key].steps.filter(Boolean).at(-1)
  if (step.errors.length) throw new Error(`capture failed: ${key}`)
  return step.sets[0].rows[0][0]
}
const encoded = Buffer.from(value('bmp-encode'), 'hex')
const decoded = Buffer.from(value('byte-decode'), 'hex')
if (encoded.length !== 65536 || decoded.length !== 512) throw new Error('incomplete code page capture')
const pairs = [...encoded].flatMap((b, u) => b === 63 ? [] : [`(${u}, ${b})`])
const units = Array.from({ length: 256 }, (_, i) => decoded.readUInt16LE(i * 2))
function rows(xs, width) { return Array.from({ length: Math.ceil(xs.length / width) }, (_, i) => `  ${xs.slice(i * width, (i + 1) * width).join(', ')},`).join('\n') }
const output = new URL('../../src/core/codepage/cp1254_data.mbt', import.meta.url)
writeFileSync(output, `// Generated by harness/src/generate-cp1254.mjs from the SQL Server oracle.\n\n///|\nlet cp1254_encoding : Array[(Int, Int)] = [\n${rows(pairs, 8)}\n]\n\n///|\nlet cp1254_decoding : FixedArray[Int] = [\n${rows(units, 16)}\n]\n`)
console.log(`wrote ${fileURLToPath(output)}: ${pairs.length} non-default encodings, 256 decodings`)
