#!/usr/bin/env python3
"""Translate pinned RE2 Unicode 15.0 reference data, preserving its license.

Source: google/re2 tag 2023-09-01. SQL behavior is verified independently by
harness/corpus/sql2025/regex-properties.sql; these tables are not test oracles.
"""
import re
from pathlib import Path
root = Path(__file__).resolve().parents[1]
vendor = root / 'docs/reference/vendor/re2'
text = (vendor / 'unicode_groups.cc').read_text()
ranges = {}
for name, body in re.findall(r'static const URange(?:16|32) (\w+)\[\] = \{(.*?)\};', text, re.S):
    ranges[name] = [(int(a), int(b)) for a, b in re.findall(r'\{ (\d+), (\d+) \}', body)]
lines = ['// Generated by scripts/gen-regex-unicode.py. RE2 Unicode 15.0 tables.',
         '// Copyright The RE2 Authors. BSD license: docs/reference/vendor/re2/LICENSE.',
         '', '///|', 'fn unicode_ranges(name : String) -> Array[(Int, Int)]? {',
         '  match name {', '    "Any" => Some([(0, 0x10FFFF)])']
for name, r16, r32 in re.findall(r'\{ "([^"]+)", \+1, (\w+), \d+, (\w+), \d+ \}', text):
    rows = ranges.get(r16, []) + ranges.get(r32, [])
    lines += [f'    "{name}" => Some([' + ','.join(f'({a},{b})' for a,b in rows) + '])']
lines += ['    _ => None', '  }', '}', '', '///|',
          'let unicode_fold_ranges : Array[(Int, Int, Int)] = [']
body = (vendor / 'unicode_casefold.cc').read_text().split('const CaseFold unicode_casefold[] = {')[1].split('};')[0]
for a,b,delta in re.findall(r'\{ (\d+), (\d+), ([\w-]+) \}',body):
    d = {'EvenOdd': '2000000', 'OddEven': '2000001'}.get(delta,delta)
    lines += [f'  ({a}, {b}, {d}),']
lines += [']', '', '///|', 'fn unicode_fold(value : Int) -> Int {',
          '  let mut low = 0', '  let mut high = unicode_fold_ranges.length()',
          '  while low < high {', '    let mid = low + (high - low) / 2',
          '    let (a, b, delta) = unicode_fold_ranges[mid]',
          '    if value < a { high = mid } else if value > b { low = mid + 1 } else {',
          '      return match delta {',
          '        2000000 => value ^ 1', '        2000001 => ((value - 1) ^ 1) + 1',
          '        _ => value + delta', '      }', '    }', '  }', '  value', '}']
(root / 'src/core/regex/unicode_data.mbt').write_text('\n'.join(lines)+'\n')
