#!/usr/bin/env python3
"""Derive graph assembly and composed search tests from oracle captures."""
import json
import math
import re
import struct
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CORPUS = ROOT / 'harness/corpus/sql2025'
def json_literal(rows):
    content = ['(', '    #|[']
    for i, row in enumerate(rows):
        suffix = ',' if i + 1 < len(rows) else ''
        content.append('    #|' + json.dumps(row, separators=(',', ':')) + suffix)
    content += ['    #|]', '  )']
    return '\n'.join(content)


lines = ['// Generated by scripts/gen-vector-build-tests.py from oracle graph captures.', '']
lines += ["""///|
fn vector_build_array(value : Json) -> Array[Json] raise {
  match value {
    Array(values) => values
    _ => fail("Expected an array in the oracle fixture")
  }
}

///|
fn vector_build_number(value : Json) -> Double raise {
  match value {
    Number(number, ..) => number
    _ => fail("Expected a number in the oracle fixture")
  }
}

///|
fn vector_build_string(value : Json) -> String raise {
  match value {
    String(text) => text
    _ => fail("Expected a string in the oracle fixture")
  }
}

///|
fn vector_build_fixture(
  text : String,
  dimensions : Int,
  base : @types.VectorBase,
) -> (Array[(Int, @types.VectorData)], Array[(Int, Array[Int])]) raise {
  let input = []
  let expected = []
  for entry in vector_build_array(@json.parse(text)) {
    let fields = vector_build_array(entry)
    let key = vector_build_number(fields[0]).to_int()
    input.push((key, @types.vector_parse(vector_build_string(fields[1]), dimensions, base~)))
    expected.push((key, vector_build_array(fields[2]).map(e => vector_build_number(e).to_int())))
  }
  expected.sort_by((a, b) => a.0.compare(b.0))
  (input, expected)
}

///|
fn vector_search_fixture(text : String) -> Array[(Int, Double)] raise {
  vector_build_array(@json.parse(text)).map(entry => {
    let fields = vector_build_array(entry)
    (vector_build_number(fields[0]).to_int(), vector_build_number(fields[1]))
  })
}
""", '']
for file in ['vector-build', 'vector-build-extended']:
    cases = json.loads((CORPUS / (file + '.cases.json')).read_text())['cases']
    expected = json.loads((CORPUS / (file + '.expected.json')).read_text())['cases']
    for case in cases:
        name = case['name']
        steps = expected[name]['steps']
        assert all(not s['errors'] for s in steps), (file, name)
        ddl = next(i for i, s in enumerate(case['steps']) if s['sql'].startswith('CREATE VECTOR INDEX'))
        setup = ' '.join(s['sql'] for s in case['steps'][:ddl])
        metric = re.search(r"METRIC='(\w+)'", case['steps'][ddl]['sql'])[1]
        dims = int(re.search(r'vector\((\d+)', setup)[1])
        base = ', base=@types.Float16' if ',float16)' in setup else ''
        dop = steps[ddl + 1]['sets'][1]['rows']
        assert len(dop) == 1 and dop[0][0] is not None, (name, dop)
        alignment = math.lcm(30, dop[0][0])
        start = json.loads(steps[ddl + 1]['sets'][0]['rows'][0][0])['StartId']
        graph = {}
        for key, data in steps[ddl + 2]['sets'][0]['rows']:
            raw = bytes.fromhex(data['value']) if data else b''
            graph[key] = sorted(struct.unpack('<' + 'i' * (len(raw) // 4), raw))
        fixture = [[int(key), vector, graph[int(key)]] for key, vector in
                   re.findall(r"\((-?\d+),'(\[[^']+\])'\)", setup)]
        assert len(fixture) == len(graph), name
        encoded = json_literal(fixture)
        vector_base = '@types.Float16' if base else '@types.Float32'
        lines += ['///|', f'test "vector build oracle {name}" {{',
                  f'  let (input, expected) = vector_build_fixture({encoded}, {dims}, {vector_base})',
                  '  let sample = input.copy()',
                  '  sample.sort_by((a, b) => a.0.compare(b.0))',
                  f'  assert_eq(@store.vector_seed(sample, @store.{metric.title()}), Some({start}))',
                  f'  let graph = @store.vector_build(input, {start}, @store.{metric.title()}, alignment={alignment})',
                  '  let nodes = graph.nodes()',
                  '  assert_eq(nodes.length(), expected.length())', '  let bad = []',
                  '  for i, node in nodes {', '    assert_eq(node.key, expected[i].0)',
                  '    let neighbors = node.neighbors.copy()', '    neighbors.sort()',
                  '    if neighbors != expected[i].1 { bad.push(node.key) }', '  }',
                  '  assert_eq(bad, [])']
        selected = 0
        for i in range(ddl + 3, len(case['steps'])):
            sql = case['steps'][i]['sql']
            top = int(re.search(r'TOP_N=(\d+)', sql)[1])
            if top not in [10, 1000]:
                continue
            q = re.search(r"@q vector\([^)]*\)='([^']+)'", sql)[1]
            rows = steps[i]['sets'][0]['rows']
            encoded_rows = json_literal([[k, float(d['value'] if isinstance(d, dict) else d)] for k, d in rows])
            lines += [f'  let result = graph.search(@types.vector_parse({json.dumps(q)}, {dims}{base}), @store.{metric.title()}, {top})',
                      f'  let expected = vector_search_fixture({encoded_rows})',
                      '  assert_eq(result.map(c => (c.key, c.distance)), expected)']
            selected += 1
            if selected == 2:
                break
        lines += ['}', '']
(ROOT / 'src/core/store/vector_build_test.mbt').write_text('\n'.join(lines))
