#!/usr/bin/env python3
"""Generates src/core/types/language_data.mbt from the oracle's sys.syslanguages
and its INFO 5703 texts, captured in harness/corpus/settings/language.expected.json
(cases 0001-syslanguages and 0000-all-languages-5703; generator
harness/gen/settings.mjs).

    python3 scripts/gen-languages.py
"""
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, 'harness/corpus/settings/language.expected.json')
OUT = os.path.join(ROOT, 'src/core/types/language_data.mbt')

cases = json.load(open(SRC))['cases']
rows = cases['0001-syslanguages']['steps'][-1]['sets'][0]['rows']
infos = [i['message'] for i in cases['0000-all-languages-5703']['steps'][-1]['info'] if i['number'] == 5703]
assert len(rows) == len(infos) == 34, (len(rows), len(infos))


def s(x):
    return json.dumps(x, ensure_ascii=False)


def arr(text):
    return '[' + ', '.join(s(p) for p in text.split(',')) + ']'


out = [
    '// Generated by scripts/gen-languages.py from the oracle\'s sys.syslanguages',
    '// (harness/corpus/settings/language.expected.json). Do not edit.',
    '',
    '///|',
    '/// The 34 languages of sys.syslanguages, by langid.',
    'pub let languages : Array[Language] = [',
]
for r, info in zip(rows, infos):
    langid, dateformat, datefirst, _upgrade, name, alias, months, shortmonths, days, lcid, msglangid = r
    out.append('  {')
    out.append(f'    langid: {langid},')
    out.append(f'    name: {s(name)},')
    out.append(f'    alias_name: {s(alias)},')
    out.append(f'    dateformat: {dateformat.strip().capitalize()},')
    out.append(f'    datefirst: {datefirst},')
    out.append(f'    months: {arr(months)},')
    out.append(f'    short_months: {arr(shortmonths)},')
    out.append(f'    days: {arr(days)},')
    out.append(f'    lcid: {lcid},')
    out.append(f'    msglangid: {msglangid},')
    out.append(f'    changed_message: {s(info)},')
    out.append('  },')
out.append(']')
open(OUT, 'w').write('\n'.join(out) + '\n')
print(f'wrote {OUT}: {len(rows)} languages')
