#!/usr/bin/env python3
"""Generates src/core/session/sysviews_data.mbt.

Inputs (both captured from real SQL Server, never hand-written):
- harness/corpus/catalog/view-descriptors.expected.json: result descriptors of
  `SELECT * FROM <view> WHERE 1 = 0` for every emulated catalog view (column
  order, wire type, nullability, computed flag, collation).
- scripts/sysviews-seed.json: seed rows of a fresh database (system objects
  in sys.objects, sys.schemas, sys.types, sys.databases), dumped from the
  oracle by harness/src/dump-sysviews-seed.mjs (node src/dump-sysviews-seed.mjs ../scripts/sysviews-seed.json) (see the sys skill findings).

Run: python3 scripts/gen-sysviews.py && moon fmt
"""
import json
import os
from datetime import datetime

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DESC = os.path.join(ROOT, 'harness/corpus/catalog/view-descriptors.expected.json')
SQL = os.path.join(ROOT, 'harness/corpus/catalog/view-descriptors.sql')
SEED = os.path.join(ROOT, 'scripts/sysviews-seed.json')
OUT = os.path.join(ROOT, 'src/core/session/sysviews_data.mbt')

SKIP = {'sys.all_objects', 'sys.all_columns', 'sys.system_objects'}


def collation(c):
    if c is None:
        return None
    key = (c['lcid'], c['flags'], c['sortId'], c['version'])
    if key == (1033, 13, 52, 0):
        return 'coll_default'
    if key == (1033, 1, 0, 0):
        return 'coll_ks_ws'
    raise SystemExit(f'unknown collation {c}')


def sql_type(c):
    t, n = c['type'], c['length']
    co = collation(c['collation'])
    if t in ('Bit', 'BitN'):
        return 'Bit'
    if t == 'TinyInt' or (t == 'IntN' and n == 1):
        return 'TinyInt'
    if t == 'SmallInt' or (t == 'IntN' and n == 2):
        return 'SmallInt'
    if t == 'Int' or (t == 'IntN' and n == 4):
        return 'Int'
    if t == 'BigInt' or (t == 'IntN' and n == 8):
        return 'BigInt'
    if t == 'DateTime':
        return 'DateTime'
    if t == 'UniqueIdentifier':
        return 'UniqueIdentifier'
    if t == 'NVarChar':
        return f'NVarChar({"None" if n == 65535 else f"Some({n // 2})"}, {co})'
    if t == 'VarChar':
        return f'VarChar({"None" if n == 65535 else f"Some({n})"}, {co})'
    if t == 'Char':
        return f'Char({n}, {co})'
    if t == 'VarBinary':
        return f'VarBinary(Some({n}))'
    if t == 'Variant':
        return None
    raise SystemExit(f'unknown type {c}')


def mbt_str(s):
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'


def datetime_value(text):
    text = text.rstrip('Z')
    d = datetime.fromisoformat(text)
    days = (d.date() - datetime(1900, 1, 1).date()).days
    secs = d.hour * 3600 + d.minute * 60 + d.second + d.microsecond / 1e6
    return f'DateTime({days}, {round(secs * 300)})'


def value(v, ty):
    if v is None:
        return 'Null'
    if ty == 'Bit':
        return f'Bit({"true" if v else "false"})'
    if ty in ('TinyInt', 'SmallInt', 'Int'):
        return f'{ty}({v})'
    if ty == 'BigInt':
        return f'BigInt({v}L)'
    if ty == 'DateTime':
        return datetime_value(v)
    if ty == 'UniqueIdentifier':
        return f'Guid(@types.parse_guid({mbt_str(v)}).unwrap())'
    if ty.startswith('VarBinary'):
        data = ''.join(f'\\x{b:02x}' for b in v['data'])
        return f'Binary(b"{data}")'
    return f'String({mbt_str(v)})'


def main():
    views = [l.split()[3] for l in open(SQL) if l.startswith('SELECT')]
    desc = json.load(open(DESC))['steps'][0]['sets']
    seed = json.load(open(SEED))
    out = []
    w = out.append
    w('// Generated by scripts/gen-sysviews.py from oracle captures')
    w('// (harness/corpus/catalog/view-descriptors.expected.json,')
    w('// scripts/sysviews-seed.json). Do not edit by hand.')
    w('')
    w('///|')
    w('/// Catalog view result descriptors, in SQL Server column order.')
    w('let view_defs : Array[ViewDef] = [')
    types_by_view = {}
    for v, s in zip(views, desc):
        if v in SKIP:
            continue
        schema, name = v.split('.')
        cols = []
        tys = {}
        for c in s['columns']:
            ty = sql_type(c)
            nullable = 'true' if c['flags'] & 1 else 'false'
            computed = 'true' if c['flags'] & 0x20 else 'false'
            if ty is None:
                cols.append(f'vc({mbt_str(c["name"])}, Bit, {nullable}, {computed}, variant=true)')
            else:
                cols.append(f'vc({mbt_str(c["name"])}, {ty}, {nullable}, {computed})')
            tys[c['name']] = ty
        types_by_view[v] = tys
        w(f'  {{ schema: {mbt_str(schema)}, name: {mbt_str(name)}, columns: [')
        for c in cols:
            w(f'    {c},')
        w('  ] },')
    w(']')
    w('')

    def seed_rows(key, view, cols=None):
        d = seed[key]
        names = d['columns']
        tys = types_by_view[view]
        rows = []
        for r in d['rows']:
            vals = []
            for n, v in zip(names, r):
                if cols is not None and n not in cols:
                    continue
                ty = tys[n] or 'Bit'
                vals.append(value(v, ty))
            rows.append('[' + ', '.join(vals) + ']')
        return names, rows

    for key, view, var in [
        ('system_objects', 'sys.objects', 'seed_system_objects'),
        ('types', 'sys.types', 'seed_types'),
        ('databases', 'sys.databases', 'seed_databases'),
    ]:
        names, rows = seed_rows(key, view)
        w('///|')
        w(f'/// Columns: {", ".join(names)}')
        w(f'let {var} : Array[Array[@types.Value]] = [')
        for r in rows:
            w(f'  {r},')
        w(']')
        w('')
    w('///|')
    w(f'let seed_database_columns : Array[String] = [{", ".join(mbt_str(n) for n in seed["databases"]["columns"])}]')
    w('')
    w('///|')
    w(f'let seed_system_object_columns : Array[String] = [{", ".join(mbt_str(n) for n in seed["system_objects"]["columns"])}]')
    w('')
    w('///|')
    w(f'let seed_type_columns : Array[String] = [{", ".join(mbt_str(n) for n in seed["types"]["columns"])}]')
    with open(OUT, 'w') as f:
        f.write('\n'.join(out) + '\n')


main()
