#!/usr/bin/env python3
"""Generate native JSON construction-size tests from SQL Server captures."""
import json
import re
from pathlib import Path
root = Path(__file__).resolve().parents[1]
out = ['// Generated by scripts/gen-json-storage-tests.py from SQL Server captures.']
count = 0
for name in ['json-binary-size', 'json-binary-boundaries']:
    document = json.loads((root / 'harness/corpus/sql2025' / f'{name}.expected.json').read_text())
    for key, case in document['cases'].items():
        step = case['steps'][0]
        if step['errors']:
            continue
        size, canonical = step['sets'][0]['rows'][0]
        # MoonBit uses Unicode scalar escapes rather than JSON's UTF-16 ones.
        literal = json.dumps(canonical, ensure_ascii=False)
        out += ['', '///|', f'test "native JSON construction storage {name} {key}" {{',
                f'  assert_eq(@types.json_constructed_storage_bytes({literal}), {size})', '}']
        count += 1
# Mutation tests consume captured canonical results as input to the allocation
# tracker; expected text and sizes remain exclusively oracle-derived.
for name in ['json-modify-allocation', 'json-allocation-sequences']:
    corpus = root / 'harness/corpus/sql2025'
    cases = json.loads((corpus / f'{name}.cases.json').read_text())['cases']
    expected = json.loads((corpus / f'{name}.expected.json').read_text())['cases']
    for case in cases:
        step = expected[case['name']]['steps'][0]
        sets = step['sets']
        if len(sets) < 2:
            continue
        initial, initial_size, _ = sets[0]['rows'][0]
        paths = re.findall(r"JSON_MODIFY\(j,N?'([^']*)',", case['steps'][0]['sql'])
        assert len(paths) == len(sets) - 1
        label = f"native JSON mutation {name} {case['name']}"
        out += ['', '///|', f'test {json.dumps(label)} {{',
                f'  let original = @types.JsonData::parse({json.dumps(initial, ensure_ascii=False)})',
                '  let mut value = original', f'  let mut previous_size = {initial_size}',
                '  let mutations : Array[(String, String, Int)] = [']
        for path, result in zip(paths, sets[1:], strict=True):
            canonical, size, _ = result['rows'][0]
            out += [f'    ({json.dumps(path)}, {json.dumps(canonical, ensure_ascii=False)}, {size}),']
        out += ['  ]', '  for (path, canonical, size) in mutations {',
                '    let previous = value', '    value = value.modified(canonical, path)',
                '    assert_eq(value.text(), canonical)',
                '    assert_eq(value.storage_bytes(), size)',
                '    assert_eq(previous.storage_bytes(), previous_size)',
                '    previous_size = size', '  }',
                f'  assert_eq(original.storage_bytes(), {initial_size})',
                f'  assert_eq(original.text(), {json.dumps(initial, ensure_ascii=False)})', '}']
        count += 1
# Compact input builders mirror the generated SQL documents. Sizes are read
# from the oracle, including the delayed dictionary-index transitions.
out += ['', '///|', 'fn json_storage_keys(n : Int, array_objects? : Bool = false) -> String {',
        '  let out = StringBuilder()',
        '  out.write_string(if array_objects { "[" } else { "{" })',
        '  for i in 0..<n {', '    if i > 0 { out.write_string(",") }',
        '    if array_objects { out.write_string("{") }',
        r'    out.write_string("\"k\{i}\":0")',
        '    if array_objects { out.write_string("}") }', '  }',
        '  out.write_string(if array_objects { "]" } else { "}" })',
        '  out.to_string()', '}']
corpus = root / 'harness/corpus/sql2025'
for name in ['json-wide-storage', 'json-dictionary-index', 'json-wide-growth',
             'json-large-cardinality', 'json-global-wide-format']:
    expected = json.loads((corpus / f'{name}.expected.json').read_text())['cases']
    for key, case in expected.items():
        if 'padding' in key:
            continue
        n = int(key.rsplit('-', 1)[1])
        array = key.startswith('array-objects-')
        if key.startswith('object-') or array:
            initial = f'json_storage_keys({n}, array_objects={str(array).lower()})'
        else:
            initial = f'"[" + "0,".repeat({n-1}) + "0]"'
            for shape, prefix, suffix in [
                ('parent-array-', '[', ']'), ('parent-object-', '{"a":', '}'),
                ('sibling-array-', '[', ',[1,2]]'),
                ('sibling-object-', '{"a":', ',"b":{"c":1,"d":2}}'),
            ]:
                if key.startswith(shape):
                    initial = f'{json.dumps(prefix)} + ({initial}) + {json.dumps(suffix)}'
                    break
        sizes = [result['rows'][0][0] for result in case['steps'][0]['sets']]
        array = key.startswith('array-')
        out += ['', '///|', f'test "native JSON wide dictionary {name} {key}" {{',
                f'  let initial = {initial}',
                '  let original = @types.JsonData::parse(initial)',
                f'  assert_eq(original.storage_bytes(), {sizes[0]})']
        if len(sizes) > 1:
            out += ['  let mut value = original', '  let mut text = initial']
            for i, size in enumerate(sizes[1:]):
                prop = 'new' if name == 'json-dictionary-index' else f'new{i}'
                suffix = ',1]' if array else f',"{prop}":1}}'
                path = 'append $' if array else f'$.{prop}'
                out += [f'  text = text.unsafe_substring(start=0, end=text.length()-1) + {json.dumps(suffix)}',
                        f'  value = value.modified(text, {json.dumps(path)})',
                        f'  assert_eq(value.storage_bytes(), {size})']
            out += [f'  assert_eq(original.storage_bytes(), {sizes[0]})']
        out += ['}']
        count += 1
(root / 'src/core/types/json_storage_oracle_test.mbt').write_text('\n'.join(out) + '\n')
print(f'Generated {count} oracle-derived JSON storage tests')
