#!/usr/bin/env python3
"""Generate native vector tests strictly from captured SQL Server results."""
import json,re
from pathlib import Path
root=Path(__file__).resolve().parents[1]
corpus=root/'harness/corpus/sql2025'
out=['// Generated by scripts/gen-vector-tests.py from SQL Server captures.']
count=0
for name in ['functions','contracts','json']:
    sql=(corpus/f'vector-{name}.sql').read_text()
    steps=re.split(r'-- @step batch\n',sql)[1:]
    expected=json.loads((corpus/f'vector-{name}.expected.json').read_text())['steps']
    for i,(step,e) in enumerate(zip(steps,expected,strict=True)):
        m=re.search(r"DECLARE @v vector\((\d+)\) =?\s*N?'([^']*)'; SELECT @v(?: AS v)?;",step)
        if not m:
            m=re.search(r"DECLARE @v vector\((\d+)\)=N?'([^']*)'; SELECT @v AS v;",step)
        if not m:continue
        dim,text=m.groups();count+=1
        out += ['', '///|',f'test "vector oracle conversion {name} {i}" {{']
        expr=f'@types.vector_parse({json.dumps(text)}, {dim})'
        if e['errors']:
            error=e['errors'][0]
            out += [f'  try {expr} catch {{',f'    e => {{ assert_eq(e.number(), {error["number"]}); assert_eq(e.state(), {error["state"]}); assert_eq(e.message(), {json.dumps(error["message"])}) }}','  } noraise { _ => fail("Expected SQL Server conversion error") }']
        else:
            value=e['sets'][0]['rows'][0][0]
            out += [f'  let v = {expr}',f'  assert_eq(v.dimensions(), {dim})',f'  assert_eq(v.to_text(), {json.dumps(value)})']
        out += ['}']
def q(value):return json.dumps(value)
def d(value):return repr(float(value))
for name in ['norms','norm-extremes']:
    inputs=re.findall(r"DECLARE @v vector\((\d+)\)='([^']*)'",(corpus/f'vector-{name}.sql').read_text())
    steps=json.loads((corpus/f'vector-{name}.expected.json').read_text())['steps']
    for i,((dim,text),step) in enumerate(zip(inputs,steps,strict=True)):
        count+=1
        out += ['', '///|', f'test "vector oracle {name} {i}" {{', f'  let v = @types.vector_parse({q(text)}, {dim})']
        if step['errors']:
            error=step['errors'][0]
            out += ['  try v.norm("norm2") catch {', f'    e => {{ assert_eq(e.number(), {error["number"]}); assert_eq(e.state(), {error["state"]}); assert_eq(e.message(), {q(error["message"])}) }}', '  } noraise { _ => fail("Expected SQL Server norm error") }']
        else:
            row=step['sets'][0]['rows'][0]
            if name=='norms':
                for j,kind in enumerate(['norm1','norm2','norminf']):
                    out += [f'  assert_eq(v.norm({q(kind)}), {d(row[2*j])})', f'  assert_eq(v.normalize({q(kind)}).to_text(), {q(row[2*j+1])})']
            else:
                out += [f'  assert_eq(v.norm("norm2"), {d(row[0])})', f'  assert_eq(v.normalize("norm2").to_text(), {q(row[1])})', f'  assert_eq(v.normalize("norm1").to_text(), {q(row[2])})']
        out += ['}']
cases=json.loads((corpus/'vector-norm-rounding.cases.json').read_text())['cases']
expected=json.loads((corpus/'vector-norm-rounding.expected.json').read_text())['cases']
for c in cases:
    count+=1
    out += ['', '///|', f'test "vector oracle norm rounding {c["name"]}" {{']
    inputs=re.findall(r"vector\((\d+)\)='([^']*)'",c['steps'][0]['sql'])
    row=expected[c['name']]['steps'][0]['sets'][0]['rows'][0]
    for i,(dim,text) in enumerate(inputs):
        out += [f'  let v{i} = @types.vector_parse({q(text)}, {dim})']
        for j,kind in enumerate(['norm1','norm2','norminf']):
            out += [f'  assert_eq(v{i}.norm({q(kind)}), {d(row[3*i+j])})']
    out += ['}']
# Distance inputs and outputs are paired directly from the recorded batches.
def distance_case(label, sql, step, base="Float32"):
    global count
    inputs=re.findall(r"vector\((\d+)(?:,float16)?\)='([^']*)'",sql)
    metrics=re.findall(r"VECTOR_DISTANCE\('([^']*)',@a,@b\)",sql)
    if len(inputs)!=2 or not metrics:return
    count+=1
    out.extend(['', '///|', f'test "vector oracle distance {label}" {{'])
    for name,(dim,text) in zip(['a','b'],inputs):
        out.append(f'  let {name} = @types.vector_parse({q(text)}, {dim}, base={base})')
    if step['errors']:
        error=step['errors'][0]
        out.extend([f'  try a.distance(b, {q(metrics[0])}) catch {{', f'    e => {{ assert_eq(e.number(), {error["number"]}); assert_eq(e.state(), {error["state"]}); assert_eq(e.message(), {q(error["message"])}) }}', '  } noraise { _ => fail("Expected SQL Server distance error") }'])
    else:
        row=step['sets'][0]['rows'][0]
        for metric,value in zip(metrics,row,strict=True):
            if isinstance(value,dict):value=float(value['value'])
            out.append(f'  assert_eq(a.distance(b, {q(metric)}), {d(value)})')
            if value==0:
                import math
                sign='true' if math.copysign(1,value)<0 else 'false'
                out.append(f'  assert_eq(1.0 / a.distance(b, {q(metric)}) < 0.0, {sign})')
    out.append('}')
for name in ['distances','distance-rounding']:
    cases=json.loads((corpus/f'vector-{name}.cases.json').read_text())['cases']
    expected=json.loads((corpus/f'vector-{name}.expected.json').read_text())['cases']
    for c in cases:
        for i,(step,e) in enumerate(zip(c['steps'],expected[c['name']]['steps'],strict=True)):
            distance_case(f'{name} {c["name"]} {i}',step['sql'],e)
for name in ['distance-special','distance-extremes']:
    sql=re.split(r'-- @step batch\n',(corpus/f'vector-{name}.sql').read_text())[1:]
    expected=json.loads((corpus/f'vector-{name}.expected.json').read_text())['steps']
    for i,(step,e) in enumerate(zip(sql,expected,strict=True)):
        distance_case(f'{name} {i}',step,e)
name='float16-distances'
cases=json.loads((corpus/f'vector-{name}.cases.json').read_text())['cases']
expected=json.loads((corpus/f'vector-{name}.expected.json').read_text())['cases']
for c in cases:
    for i,(step,e) in enumerate(zip(c['steps'],expected[c['name']]['steps'],strict=True)):
        distance_case(f'{name} {c["name"]} {i}',step['sql'],e,'Float16')
name='float16-values'
steps=re.split(r'-- @step batch\n',(corpus/f'vector-{name}.sql').read_text())[1:]
expected=json.loads((corpus/f'vector-{name}.expected.json').read_text())['steps']
for i,(sql,e) in enumerate(zip(steps,expected,strict=True)):
    m=re.search(r"DECLARE @v vector\((\d+),float16\)='([^']*)'; SELECT @v AS v",sql)
    if not m:continue
    count+=1;dim,value=m.groups()
    out.extend(['', '///|',f'test "vector oracle float16 input {i}" {{'])
    expr=f'@types.vector_parse({q(value)}, {dim}, base=Float16)'
    if e['errors']:
        error=e['errors'][0]
        out.extend([f'  try {expr} catch {{',f'    e => {{ assert_eq(e.number(), {error["number"]}); assert_eq(e.state(), {error["state"]}); assert_eq(e.message(), {q(error["message"])}) }}','  } noraise { _ => fail("Expected SQL Server float16 input error") }'])
    else:
        row=e['sets'][0]['rows'][0]
        out.extend([f'  let v = {expr}', f'  assert_eq(v.to_text(), {q(row[0])})',f'  assert_eq(8 + v.base().bytes() * v.dimensions(), {row[1]})',f'  assert_eq(v.base().name(), {q(row[2])})'])
    out.append('}')
(root/'src/core/types/vector_test.mbt').write_text('\n'.join(out)+'\n')
print(count,'oracle vector tests')
