#!/usr/bin/env python3
"""Generates src/core/types/case_data.mbt: UPPER/LOWER of every UTF-16 code
unit as SQL Server maps it, for version-0 collations (SQL_Latin1_General_CP1_*,
Latin1_General_*) and version-100 collations (Latin1_General_100_*), from the
captured msduck unicode-case mappings
(harness/corpus/msduck-runs/unicode-case.expected.json, cases
001-sql-latin1-general-cp1-ci-as-mapping and 012-latin1-general-100-ci-as-mapping;
every _100 collation, BIN2 included, maps alike).

    python3 scripts/gen-case-map.py
"""
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, 'harness/corpus/msduck-runs/unicode-case.expected.json')
OUT = os.path.join(ROOT, 'src/core/types/case_data.mbt')

cases = json.load(open(SRC))['cases']


def rows(name):
    return [tuple(r) for r in cases[name]['steps'][-1]['sets'][0]['rows']]


def table(name, label, comment):
    out = ['///|', f'/// {comment}', f'let {label} : Array[(Int, Int, Int)] = [']
    line = ' '
    for unit, lower, upper in rows(name):
        item = f' ({unit}, {lower}, {upper}),'
        if len(line) + len(item) > 88:
            out.append(line)
            line = ' '
        line += item
    out.append(line)
    out.append(']')
    return out


lines = [
    '// Generated by scripts/gen-case-map.py from captured SQL Server case',
    '// mappings (harness/corpus/msduck-runs/unicode-case.expected.json). Do not',
    '// edit. Rows: (unit, LOWER, UPPER) for every UTF-16 unit LOWER or UPPER',
    '// changes, sorted by unit.',
    '',
]
lines += table('001-sql-latin1-general-cp1-ci-as-mapping', 'case_map_v0', 'Version-0 collations.')
lines.append('')
lines += table('012-latin1-general-100-ci-as-mapping', 'case_map_v100', 'Version-100 collations.')
open(OUT, 'w').write('\n'.join(lines) + '\n')
print(f'wrote {OUT}')
