#!/usr/bin/env python3
"""Generate native JSON construction-size tests from SQL Server captures."""
import json
import re
from pathlib import Path
root = Path(__file__).resolve().parents[1]
out = ['// Generated by scripts/gen-json-storage-tests.py from SQL Server captures.']
count = 0
for name in ['json-binary-size', 'json-binary-boundaries']:
    document = json.loads((root / 'harness/corpus/sql2025' / f'{name}.expected.json').read_text())
    for key, case in document['cases'].items():
        step = case['steps'][0]
        if step['errors']:
            continue
        size, canonical = step['sets'][0]['rows'][0]
        # MoonBit uses Unicode scalar escapes rather than JSON's UTF-16 ones.
        literal = json.dumps(canonical, ensure_ascii=False)
        out += ['', '///|', f'test "native JSON construction storage {name} {key}" {{',
                f'  assert_eq(@types.json_constructed_storage_bytes({literal}), {size})', '}']
        count += 1
# Mutation tests consume captured canonical results as input to the allocation
# tracker; expected text and sizes remain exclusively oracle-derived.
for name in ['json-modify-allocation', 'json-allocation-sequences']:
    corpus = root / 'harness/corpus/sql2025'
    cases = json.loads((corpus / f'{name}.cases.json').read_text())['cases']
    expected = json.loads((corpus / f'{name}.expected.json').read_text())['cases']
    for case in cases:
        step = expected[case['name']]['steps'][0]
        sets = step['sets']
        if len(sets) < 2:
            continue
        initial, initial_size, _ = sets[0]['rows'][0]
        paths = re.findall(r"JSON_MODIFY\(j,N?'([^']*)',", case['steps'][0]['sql'])
        assert len(paths) == len(sets) - 1
        label = f"native JSON mutation {name} {case['name']}"
        out += ['', '///|', f'test {json.dumps(label)} {{',
                f'  let original = @types.JsonData::parse({json.dumps(initial, ensure_ascii=False)})',
                '  let mut value = original', f'  let mut previous_size = {initial_size}',
                '  let mutations : Array[(String, String, Int)] = [']
        for path, result in zip(paths, sets[1:], strict=True):
            canonical, size, _ = result['rows'][0]
            out += [f'    ({json.dumps(path)}, {json.dumps(canonical, ensure_ascii=False)}, {size}),']
        out += ['  ]', '  for (path, canonical, size) in mutations {',
                '    let previous = value', '    value = value.modified(canonical, path)',
                '    assert_eq(value.text(), canonical)',
                '    assert_eq(value.storage_bytes(), size)',
                '    assert_eq(previous.storage_bytes(), previous_size)',
                '    previous_size = size', '  }',
                f'  assert_eq(original.storage_bytes(), {initial_size})',
                f'  assert_eq(original.text(), {json.dumps(initial, ensure_ascii=False)})', '}']
        count += 1
(root / 'src/core/types/json_storage_oracle_test.mbt').write_text('\n'.join(out) + '\n')
print(f'Generated {count} oracle-derived JSON storage tests')
