#!/usr/bin/env python3
"""Generate pure graph-pruning tests from captured SQL Server graph pages."""
import json
import re
import struct
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CORPUS = ROOT / 'harness/corpus/sql2025'
cases = json.loads((CORPUS / 'vector-pruning.cases.json').read_text())['cases']
expected = json.loads((CORPUS / 'vector-pruning.expected.json').read_text())['cases']
lines = ['// Generated by scripts/gen-vector-pruning-tests.py from SQL Server graph captures.', '']
node_count = 0
for case in cases:
    name = case['name']
    metric = re.search(r"METRIC='(\w+)'", case['steps'][1]['sql'])[1]
    metric_enum = {'cosine':'Cosine','euclidean':'Euclidean','dot':'Dot'}[metric]
    setup = case['steps'][0]['sql']
    dimensions = int(re.search(r'v vector\((\d+)\)', setup)[1])
    inputs = re.findall(r"\((-?\d+),'(\[[^']+\])'\)", setup)
    capture = expected[name]
    assert all(not step['errors'] for step in capture['steps']), name
    rows = capture['steps'][2]['sets'][0]['rows']
    assert len(rows) == len(inputs), name
    lines += ['///|', f'test "vector pruning oracle {name}" {{',
              '  let vectors : Array[(Int, @types.VectorData)] = [']
    for key, text in inputs:
        lines.append(f'    ({key}, @types.vector_parse({json.dumps(text)}, {dimensions})),')
    lines += ['  ]', '  let expected : Array[(Int, Array[Int])] = [']
    for key, value in rows:
        assert value['kind'] == 'binary', (name, key)
        data = bytes.fromhex(value['value'])
        assert len(data) % 4 == 0
        neighbors = list(struct.unpack('<' + 'i' * (len(data) // 4), data))
        assert len(neighbors) <= 48
        lines.append(f'    ({key}, {json.dumps(neighbors)}),')
        node_count += 1
    lines += ['  ]', '  for (key, neighbors) in expected {',
              '    let source = vectors[vectors.search_by(v => v.0 == key).unwrap()].1',
              '    let candidates : Array[@store.VectorCandidate] = []',
              '    for (candidate_key, vector) in vectors {',
              '      if candidate_key != key {',
              '        candidates.push({',
              '          key: candidate_key,',
              '          vector,',
              f'          distance: source.distance(vector, "{metric}"),',
              '        })', '      }', '    }',
              '    candidates.sort_by((a, b) => a.distance.compare(b.distance))',
              f'    assert_eq(@store.vector_prune(candidates, @store.{metric_enum}), neighbors)',
              '  }', '}', '']
(ROOT / 'src/core/store/vector_prune_test.mbt').write_text('\n'.join(lines))
print(f'Generated {len(cases)} pruning tests checking {node_count} captured neighbor lists')
