#!/usr/bin/env python3
"""Generate native JSON construction-size tests from SQL Server captures."""
import json
from pathlib import Path
root = Path(__file__).resolve().parents[1]
out = ['// Generated by scripts/gen-json-storage-tests.py from SQL Server captures.']
count = 0
for name in ['json-binary-size', 'json-binary-boundaries']:
    document = json.loads((root / 'harness/corpus/sql2025' / f'{name}.expected.json').read_text())
    for key, case in document['cases'].items():
        step = case['steps'][0]
        if step['errors']:
            continue
        size, canonical = step['sets'][0]['rows'][0]
        # MoonBit uses Unicode scalar escapes rather than JSON's UTF-16 ones.
        literal = json.dumps(canonical, ensure_ascii=False)
        out += ['', '///|', f'test "native JSON construction storage {name} {key}" {{',
                f'  assert_eq(@types.json_constructed_storage_bytes({literal}), {size})', '}']
        count += 1
(root / 'src/core/types/json_storage_oracle_test.mbt').write_text('\n'.join(out) + '\n')
print(f'Generated {count} oracle-derived JSON storage tests')
