#!/usr/bin/env python3
"""Generate seed selection assertions from captured build_parameters."""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CORPUS = ROOT / 'harness/corpus/sql2025'
lines = ['// Generated by scripts/gen-vector-seed-tests.py from oracle captures.', '']
for file in ['vector-seed']:
    cases = json.loads((CORPUS / (file + '.cases.json')).read_text())['cases']
    expected = json.loads((CORPUS / (file + '.expected.json')).read_text())['cases']
    for case in cases:
        name = case['name']
        steps = expected[name]['steps']
        assert all(not s['errors'] for s in steps), (file, name)
        ddl = next(i for i, s in enumerate(case['steps']) if s['sql'].startswith('CREATE VECTOR INDEX'))
        setup = ' '.join(s['sql'] for s in case['steps'][:ddl])
        metric = re.search(r"METRIC='(\w+)'", case['steps'][ddl]['sql'])[1]
        dims = int(re.search(r'vector\((\d+)', setup)[1])
        base = ', base=@types.Float16' if ',float16)' in setup else ''
        start = json.loads(steps[ddl + 1]['sets'][0]['rows'][0][0])['StartId']
        lines += ['///|', f'test "vector seed oracle {name}" {{',
                  '  let input : Array[(Int, @types.VectorData)] = [']
        for key, vector in re.findall(r"\((-?\d+),'(\[[^']+\])'\)", setup):
            lines.append(f'    ({key}, @types.vector_parse({json.dumps(vector)}, {dims}{base})),')
        lines += ['  ]', '  input.sort_by((a, b) => a.0.compare(b.0))',
                  f'  assert_eq(@store.vector_seed(input, @store.{metric.title()}), Some({start}))', '}', '']
(ROOT / 'src/core/store/vector_seed_test.mbt').write_text('\n'.join(lines))
