#!/usr/bin/env python3
"""Derive graph search inputs and outputs from SQL Server oracle captures."""
import json,re,struct
from pathlib import Path
root=Path(__file__).resolve().parents[1]
corpus=root/'harness/corpus/sql2025'
cases=json.loads((corpus/'vector-search-traversal.cases.json').read_text())['cases']
expected=json.loads((corpus/'vector-search-traversal.expected.json').read_text())['cases']
lines=['// Generated by scripts/gen-vector-search-tests.py from oracle captures.','']
for case in cases:
 name=case['name']; steps=expected[name]['steps']
 assert all(not s['errors'] for s in steps),name
 metric,dims,_=name.split('-'); dims=int(dims)
 params=json.loads(steps[2]['sets'][0]['rows'][0][0])
 start=params['StartId']
 graph={}
 for key,data in steps[3]['sets'][0]['rows']:
  raw=bytes.fromhex(data['value']) if data else b''
  graph[key]=list(struct.unpack('<'+'i'*(len(raw)//4),raw))
 lines+=['///|',f'test "vector search oracle {name}" {{','  let nodes : Array[@store.VectorNode] = [']
 for key,vector in re.findall(r"\((-?\d+),'(\[[^']+\])'\)",case['steps'][0]['sql']):
  lines.append(f'    {{ key: {key}, vector: @types.vector_parse({json.dumps(vector)}, {dims}), neighbors: {json.dumps(graph[int(key)])} }},')
 lines+=['  ]']
 for i,step in enumerate(case['steps'][4:],4):
  q=re.search(r"@q vector\(\d+\)='([^']+)'",step['sql'])[1]
  top=int(re.search(r'TOP_N=(\d+)',step['sql'])[1])
  rows=steps[i]['sets'][0]['rows']
  pairs=', '.join('('+str(k)+', '+repr(float(d["value"] if isinstance(d,dict) else d))+')' for k,d in rows)
  lines += [f'  let expected : Array[(Int, Double)] = [{pairs}]',f'  let found = @store.vector_search(nodes, {start}, @types.vector_parse({json.dumps(q)}, {dims}), @store.{metric.title()}, {top})']
  if all(v == 0 for v in json.loads(q)) and metric != 'euclidean':
   lines += ['  // All source rows tie; oracle rebuilds can change the chosen keys.', f'  assert_eq(found.map(c => c.distance), expected.map(c => c.1), msg="{name} step {i}")']
   lines += ['  let keys : Set[Int] = Set([])', '  for candidate in found {', '    assert_true(!keys.contains(candidate.key))', '    assert_true(nodes.any(n => n.key == candidate.key))', '    keys.add(candidate.key) |> ignore', '  }']
  else:
   lines += [f'  assert_eq(found.map(c => (c.key, c.distance)), expected, msg="{name} step {i}")']
 lines+=['}','']
(root/'src/core/store/vector_search_test.mbt').write_text('\n'.join(lines))
