#!/usr/bin/env python3
"""Generate pure regex engine tests from SQL Server corpus captures.

The SQL inputs below select corresponding captured REGEXP_COUNT columns.
Expected values and error details are always read from the oracle artifacts.
"""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CORPUS = ROOT / 'harness/corpus/sql2025'

def captured(name, step):
    return json.loads((CORPUS / f'regex-{name}.expected.json').read_text())['steps'][step]

def q(s):
    # MoonBit quoted strings accept literal Unicode. Escape controls explicitly.
    return json.dumps(s, ensure_ascii=False)

counts = [
    ('functions', 0, 0, 'Ab12cd34', '[0-9]+', ''),
    ('functions', 3, 0, 'aaa', 'a*', ''),
    ('functions', 5, 0, 'abc', '', ''),
    ('boundaries', 1, 0, 'abc123', 'a{', ''),
    ('boundaries', 9, 0, 'abc123', '(?:a)', ''),
    ('boundaries', 10, 0, 'abc123', '(?i)a', ''),
    ('boundaries', 11, 0, 'abc123', 'a*?', ''),
    ('boundaries', 13, 0, 'abc123', '[[:digit:]]', ''),
    ('boundaries', 15, 0, 'abc123', r'\b', ''),
    ('boundaries', 21, 0, 'A', 'a', 'ci'),
    ('boundaries', 22, 0, 'A', 'a', 'ic'),
    ('boundaries', 24, 0, 'A', 'a', ''),
    ('boundaries', 26, 0, 'A', 'a', 'ii'),
    ('boundaries', 27, 0, 'A', 'a', 'iscm'),
    ('unicode', 0, 0, 'a😀b', '.', ''),
    ('unicode', 1, 0, '😀', '.', ''),
    ('unicode', 1, 1, '😀', r'\C', ''),
    ('unicode', 5, 0, 'A', 'a', ''),
    ('unicode', 5, 1, 'é', 'e', ''),
    ('unicode', 6, 0, 'a\nb', '^b', 'm'),
    ('unicode', 6, 1, 'a\nb', '.', 's'),
    ('unicode', 7, 0, 'a\n', 'a$', ''),
    ('unicode', 7, 1, 'a\n', 'a$', 'm'),
    ('unicode', 8, 0, 'aaa', 'a*?', ''),
]
errors = [
    ('functions', 6, '(', ''), ('functions', 8, 'a', 'x'),
    ('boundaries', 0, '[', ''), ('boundaries', 2, 'a{2,1}', ''),
    ('boundaries', 3, '*', ''), ('boundaries', 4, r'\q', ''),
    ('boundaries', 5, '(?=a)', ''), ('boundaries', 6, '(?<=a)', ''),
    ('boundaries', 7, r'(a)\1', ''), ('boundaries', 8, '[z-a]', ''),
    ('boundaries', 12, 'a{1001}', ''), ('boundaries', 23, 'a', 'I'),
    ('boundaries', 28, 'a', 'xxz'),
]
# Property syntax and simple-fold controls, independently captured in SQL.
property_sql = (CORPUS / 'regex-properties.sql').read_text()
for step, (text, pattern, flags) in enumerate(re.findall(
    r"SELECT REGEXP_COUNT\(N'([^']*)', N'([^']*)'(?:,1,'([^']*)')?\)", property_sql)):
    if captured('properties', step)['errors']:
        errors.append(('properties', step, pattern, flags))
    else:
        counts.append(('properties', step, 0, text, pattern, flags))

out = ['// Generated by scripts/gen-regex-tests.py from real SQL Server captures.',
       '// Do not hand-edit expectations.', '', '///|',
       'fn count_matches(text : String, pattern : String, flags : String) -> Int raise {',
       '  let p = @regex.compile(pattern, flags)', '  let bytes = @utf8.encode(text)',
       '  let mut at = 0', '  let mut count = 0',
       '  while p.find(bytes, at, _ => ()) is Some(m) {',
       '    let (start, end) = m.groups[0].unwrap()', '    count += 1',
       '    at = if start == end { @regex.next_boundary(bytes, end) } else { end }',
       '  }', '  count', '}']
for name, step, col, text, pattern, flags in counts:
    expected = captured(name, step)['sets'][0]['rows'][0][col]
    out += ['', '///|', f'test "oracle count {name} {step} {col}" {{',
            f'  assert_eq(count_matches({q(text)}, {q(pattern)}, {q(flags)}), {expected})', '}']
for name, step, pattern, flags in errors:
    error = captured(name, step)['errors'][0]
    out += ['', '///|', f'test "oracle syntax {name} {step}" {{',
            f'  try @regex.compile({q(pattern)}, {q(flags)}) catch {{',
            f'    e => {{ assert_eq(e.number(), {error["number"]}); assert_eq(e.state(), {error["state"]}); assert_eq(e.message(), {q(error["message"])}) }}',
            '  } noraise { _ => fail("Expected the oracle pattern error") }', '}']
out += ['', '///|',
        'fn capture_values(text : String, pattern : String) -> Array[Array[String?]] raise {',
        '  let p = @regex.compile(pattern, "")',
        '  let bytes = @utf8.encode(text)',
        '  let rows : Array[Array[String?]] = []',
        '  let mut at = 0',
        '  while p.find(bytes, at, _ => ()) is Some(m) {',
        '    rows.push(m.groups.map(g => match g {',
        '      None => None',
        '      Some((a, b)) => Some(@utf8.decode(bytes[a:b]))',
        '    }))',
        '    let (a, b) = m.groups[0].unwrap()',
        '    at = if a == b { @regex.next_boundary(bytes, b) } else { b }',
        '  }', '  rows', '}']
pairs = re.findall(r"REGEXP_MATCHES\('([^']*)', '([^']*)'\)", (CORPUS / 'regex-captures.sql').read_text())
for step, (text, pattern) in enumerate(pairs):
    values = []
    for row in captured('captures', step)['sets'][0]['rows']:
        groups = [] if step in (14, 15, 18, 19) else [g['value'] for g in json.loads(row[4])]
        vals = [row[3], *groups]
        values.append('[' + ', '.join('None' if v is None else f'Some({q(v)})' for v in vals) + ']')
    expected = '[' + ', '.join(values) + ']'
    out += ['', '///|', f'test "oracle captures {step}" {{',
            f'  assert_eq(capture_values({q(text)}, {q(pattern)}), {expected})', '}']
(ROOT / 'src/core/regex/oracle_test.mbt').write_text('\n'.join(out) + '\n')
