#!/usr/bin/env python3
"""Generate pure response-decoder tests from the real HTTPS oracle capture."""
import json
from pathlib import Path
root = Path(__file__).resolve().parent.parent
captured = json.loads((root / 'harness/fixtures/embeddings.expected.json').read_text())
q = lambda s: json.dumps(s, ensure_ascii=False)
out = ['// Generated by scripts/gen-embedding-tests.py from HTTPS oracle captures.\n']
count = 0
for entry in captured['cases']:
    c, result = entry['input'], entry['result']
    if len(entry['requests']) != 1:
        continue  # Binding / request validation failed before response decoding.
    body = c['response']['body']
    if not isinstance(body, str):
        body = json.dumps(body, ensure_ascii=False, separators=(',', ':'))
    api = {'OpenAI': 'OpenAI', 'Azure OpenAI': 'AzureOpenAI', 'Ollama': 'Ollama'}[c['api']]
    call = f'@types.embedding_response({api}, {c["response"].get("status", 200)}, {q(body)})'
    out += ['///|', f'test {q("embedding response " + c["name"])} {{']
    if result['errors']:
        assert len(result['errors']) == 1
        e = result['errors'][0]
        out += [f'  try {call} catch {{', '    e => {',
                f'      assert_eq(e.number(), {e["number"]})',
                f'      assert_eq(e.state(), {e["state"]})',
                f'      assert_eq(e.severity(), {e["class"]})',
                f'      assert_eq(e.message(), {q(e["message"])})',
                '    }', '  } noraise { _ => fail("expected captured SQL error") }']
    else:
        value = result['sets'][0]['rows'][0][0]
        if value is None:
            out += [f'  assert_eq({call}, @types.Value::Null)']
        else:
            out += [f'  match {call} {{', f'    NativeJson(v) => assert_eq(v.text(), {q(value)})',
                    '    _ => fail("expected native JSON")', '  }']
    out += ['}', '']
    count += 1
request_count = 0
for entry in captured['cases']:
    c, result = entry['input'], entry['result']
    api = {'OpenAI': 'OpenAI', 'Azure OpenAI': 'AzureOpenAI', 'Ollama': 'Ollama'}[c['api']]
    source = 'None' if c['sourceText'] is None else 'Some(' + q(c['sourceText']) + ')'
    parameters = 'None' if 'parameters' not in c else 'Some(@types.JsonData::parse(' + q(json.dumps(c['parameters'], ensure_ascii=False, separators=(',', ':'))) + '))'
    optional = 'None' if c['optional'] is None else 'Some(@types.JsonData::parse(' + q(c['optional']) + '))'
    call = f'@types.embedding_request({api}, {q(c.get("model", "fixture"))}, {source}, {parameters}, {optional})'
    out += ['///|', f'test {q("embedding request " + c["name"])} {{']
    if entry['requests']:
        assert all(r['body'] == entry['requests'][0]['body'] for r in entry['requests'])
        out += [f'  let request = {call}', f'  assert_eq(request.body, {q(entry["requests"][0]["body"])})']
        if c['response'].get('status') in (408, 429, 500, 502, 503, 504):
            out += [f'  assert_eq(request.retry_count, {len(entry["requests"]) - 1})']
    else:
        assert len(result['errors']) == 1
        e = result['errors'][0]
        out += [f'  try {call} catch {{', '    e => {',
                f'      assert_eq(e.number(), {e["number"]})',
                f'      assert_eq(e.state(), {e["state"]})',
                f'      assert_eq(e.severity(), {e["class"]})',
                f'      assert_eq(e.message(), {q(e["message"])})',
                '    }', '  } noraise { _ => fail("expected captured SQL error") }']
    out += ['}', '']
    request_count += 1
(root / 'src/core/types/embedding_oracle_test.mbt').write_text('\n'.join(out))
print(f'generated {count} response and {request_count} request tests')
