// Prisma 7: the CLI's schema engine (Rust, its own TDS client: tiberius)
// runs `migrate deploy` (sp_getapplock + _prisma_migrations), `migrate
// status`, `migrate diff` against the live database (must be empty after
// deploy), `db push` into a second database and `db pull --print`
// (introspection of the whole catalog). The client (query compiler +
// @prisma/adapter-mssql over the `mssql` package, no query engine binary)
// runs CRUD, nested writes, relations, aggregates, batch and interactive
// transactions with isolation levels, and $queryRaw / $executeRaw.
//
// The client is generated by `npx prisma generate` (run.mjs does it once
// when prisma/generated is missing).
import { execFile } from 'node:child_process'
import { existsSync } from 'node:fs'
import { createRequire } from 'node:module'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { promisify } from 'node:util'
import { freshDatabase, dropDatabase } from '../lib/targets.mjs'

const run = promisify(execFile)
const here = join(dirname(fileURLToPath(import.meta.url)), '..')
const require = createRequire(import.meta.url)
const prismaCli = join(here, 'node_modules', 'prisma', 'build', 'index.js')

function url(t, database) {
  return `sqlserver://${t.host}:${t.port};database=${database};user=${t.user};password={${t.password}};encrypt=${t.encrypt};trustServerCertificate=true;connectTimeout=30`
}

async function cli(t, database, args) {
  const env = { ...process.env, DATABASE_URL: url(t, database), CHECKPOINT_DISABLE: '1', PRISMA_HIDE_UPDATE_MESSAGE: '1', NO_COLOR: '1', FORCE_COLOR: '0' }
  let code = 0
  let stdout = ''
  let stderr = ''
  try {
    ({ stdout, stderr } = await run(process.execPath, [prismaCli, ...args], { cwd: here, env, timeout: 180000, maxBuffer: 16 << 20 }))
  } catch (error) {
    code = error.code ?? 1
    stdout = error.stdout ?? ''
    stderr = error.stderr ?? String(error.message)
  }
  const clean = s => s.split('\n')
    .map(l => l.replace(/\x1b\[[0-9;]*m/g, '').replace(/\d+(\.\d+)?m?s\b/g, '{ms}').replace(new RegExp(`${t.host}:${t.port}`, 'g'), '{addr}').trimEnd())
    .filter(l => l && !/^Loaded Prisma config|^Prisma schema loaded|^Environment variables loaded|^warn |Update available|pris\.ly\/d\/major/.test(l))
  if (code && process.env.ORM_DEBUG) console.error(`[${t.name}] prisma ${args.join(' ')} exited ${code}\n${stdout}\n${stderr}`)
  return { code, stdout: clean(stdout), stderr: code ? clean(stderr).slice(0, 12) : [] }
}

export async function ensureClient() {
  if (existsSync(join(here, 'prisma', 'generated', 'client', 'index.js'))) return
  await run(process.execPath, [prismaCli, 'generate'], { cwd: here, env: { ...process.env, CHECKPOINT_DISABLE: '1' } })
}

export default async function prismaWorkload(t, trace) {
  await ensureClient()
  const step = trace.step.bind(trace)
  const pushDb = `${t.database}_push`
  const db = t.database

  // CLI / schema engine
  await step('migrate deploy', () => cli(t, db, ['migrate', 'deploy']), { sql: false })
  await step('migrate status', () => cli(t, db, ['migrate', 'status']), { sql: false })
  await step('migrate deploy again (no-op)', () => cli(t, db, ['migrate', 'deploy']), { sql: false })
  await step('migrate diff db -> schema (empty)', () => cli(t, db, ['migrate', 'diff', '--from-config-datasource', '--to-schema', 'prisma/schema.prisma', '--script']), { sql: false })
  await step('db pull --print', () => cli(t, db, ['db', 'pull', '--print']), { sql: false })
  await step('db push (second database)', async () => { await freshDatabase(t, pushDb); return cli(t, pushDb, ['db', 'push']) }, { sql: false })
  await step('db push again (in sync)', () => cli(t, pushDb, ['db', 'push']), { sql: false })
  await step('migrate diff pushed db -> schema (empty)', () => cli(t, pushDb, ['migrate', 'diff', '--from-config-datasource', '--to-schema', 'prisma/schema.prisma', '--script']), { sql: false })
  await step('db pull --print (pushed)', () => cli(t, pushDb, ['db', 'pull', '--print']), { sql: false })
  if (t.name === 'oracle') await dropDatabase(t, pushDb)

  // Client
  const { PrismaClient, Prisma } = require(join(here, 'prisma', 'generated', 'client', 'index.js'))
  const { PrismaMssql } = await import('@prisma/adapter-mssql')
  const adapter = new PrismaMssql({
    server: t.host, port: t.port, user: t.user, password: t.password, database: db,
    options: { encrypt: t.encrypt, trustServerCertificate: true },
    pool: { max: 3, min: 0 },
  })
  const prisma = new PrismaClient({ adapter, log: [{ emit: 'event', level: 'query' }] })
  prisma.$on('query', e => trace.logSql(e.query))
  try {
    await step('$connect', () => prisma.$connect())
    await step('_prisma_migrations rows', () => prisma.$queryRaw`SELECT migration_name, checksum, applied_steps_count, logs, CASE WHEN finished_at IS NULL THEN 0 ELSE 1 END AS finished, rolled_back_at FROM _prisma_migrations ORDER BY migration_name`)
    await step('create nested', () => prisma.user.create({
      data: {
        email: 'ada@example.com', name: 'Ada', age: 36, karma: 9007199254740993n, balance: '10.50', score: 0.25,
        born: new Date('1815-12-10T00:00:00Z'), seenAt: new Date('2020-01-02T03:04:05.678Z'), bio: 'x'.repeat(5000),
        avatar: Buffer.from('cafe', 'hex'), token: '7D444840-9DC0-11D1-B245-5FFDCE74FAD2',
        profile: { create: { website: 'https://example.com' } },
        posts: { create: [{ title: 'Hello', body: 'one', tags: { create: [{ name: 'red' }, { name: 'green' }] } }, { title: 'World' }] },
      },
      include: { profile: true, posts: { include: { tags: { orderBy: { id: 'asc' } } }, orderBy: { id: 'asc' } } },
    }).then(u => ({ ...u, bio: u.bio.length })))
    await step('createMany', () => prisma.user.createMany({ data: [{ email: 'bob@example.com', name: 'Bob', age: 40 }, { email: 'cy@example.com', name: 'Cy', active: false }] }))
    await step('createManyAndReturn (unsupported on sqlserver)', () => prisma.user.createManyAndReturn?.({ data: [{ email: 'zz@example.com', name: 'Zz' }] }) ?? 'n/a')
    await step('unique violation P2002', () => prisma.user.create({ data: { email: 'ada@example.com', name: 'Dup' } }))
    await step('fk violation P2003', () => prisma.post.create({ data: { title: 'orphan', authorId: 999 } }))
    await step('findUnique include', () => prisma.user.findUnique({ where: { email: 'ada@example.com' }, select: { id: true, name: true, karma: true, balance: true, avatar: true, token: true, born: true, seenAt: true, profile: { select: { website: true } }, posts: { select: { title: true, tags: { select: { name: true }, orderBy: { name: 'asc' } } }, orderBy: { id: 'asc' } } } }))
    await step('findMany filters skip take', () => prisma.user.findMany({ where: { OR: [{ age: { gt: 30 } }, { name: { startsWith: 'C' } }], email: { contains: 'example' } }, orderBy: [{ name: 'desc' }], skip: 1, take: 2, select: { id: true, name: true } }))
    await step('findMany insensitive + in + not', () => prisma.user.findMany({ where: { name: { in: ['Ada', 'Bob'] }, NOT: { age: null } }, select: { name: true }, orderBy: { id: 'asc' } }))
    await step('cursor pagination', () => prisma.user.findMany({ cursor: { id: 2 }, skip: 1, take: 5, orderBy: { id: 'asc' }, select: { id: true } }))
    await step('relation filters some/none/every', async () => ({
      some: await prisma.user.findMany({ where: { posts: { some: { title: { contains: 'o' } } } }, select: { name: true } }),
      none: await prisma.user.findMany({ where: { posts: { none: {} } }, select: { name: true }, orderBy: { id: 'asc' } }),
      every: await prisma.post.findMany({ where: { tags: { every: { name: { not: 'blue' } } } }, select: { title: true }, orderBy: { id: 'asc' } }),
    }))
    await step('count / aggregate / groupBy', async () => ({
      count: await prisma.user.count(),
      relCount: await prisma.user.findMany({ select: { name: true, _count: { select: { posts: true } } }, orderBy: { id: 'asc' } }),
      agg: await prisma.user.aggregate({ _sum: { age: true, balance: true }, _avg: { age: true }, _max: { karma: true }, _count: { _all: true, age: true } }),
      group: await prisma.post.groupBy({ by: ['authorId'], _count: { _all: true }, orderBy: { authorId: 'asc' }, having: { authorId: { _count: { gt: 0 } } } }),
    }))
    await step('distinct', () => prisma.post.findMany({ distinct: ['authorId'], select: { authorId: true }, orderBy: { authorId: 'asc' } }))
    await step('update nested', () => prisma.user.update({ where: { email: 'bob@example.com' }, data: { age: { increment: 1 }, posts: { create: { title: 'Boat' } }, profile: { upsert: { create: { website: 'b.example' }, update: { website: 'b2.example' } } } }, select: { age: true, profile: { select: { website: true } } } }))
    await step('updateMany', () => prisma.post.updateMany({ where: { views: 0 }, data: { views: { increment: 3 } } }))
    await step('upsert create', () => prisma.tag.upsert({ where: { name: 'blue' }, create: { name: 'blue' }, update: {} }))
    await step('upsert update', () => prisma.tag.upsert({ where: { name: 'blue' }, create: { name: 'blue' }, update: { name: 'navy' } }))
    await step('connect / disconnect m2m', async () => {
      await prisma.post.update({ where: { id: 2 }, data: { tags: { connect: [{ name: 'red' }, { name: 'navy' }] } } })
      await prisma.post.update({ where: { id: 2 }, data: { tags: { disconnect: [{ name: 'red' }] } } })
      return prisma.post.findUnique({ where: { id: 2 }, select: { tags: { select: { name: true }, orderBy: { name: 'asc' } } } })
    })
    await step('batch $transaction', () => prisma.$transaction([prisma.tag.create({ data: { name: 'batch-1' } }), prisma.tag.count()]))
    await step('batch $transaction rollback', async () => {
      try { await prisma.$transaction([prisma.tag.create({ data: { name: 'batch-2' } }), prisma.tag.create({ data: { name: 'red' } })]) } catch (e) { return { code: e.code, left: await prisma.tag.count({ where: { name: 'batch-2' } }) } }
    })
    await step('interactive transaction serializable', () => prisma.$transaction(async tx => {
      await tx.tag.create({ data: { name: 'itx' } })
      return tx.$queryRaw`SELECT transaction_isolation_level AS level, @@TRANCOUNT AS tc FROM sys.dm_exec_sessions WHERE session_id = @@SPID`
    }, { isolationLevel: Prisma.TransactionIsolationLevel.Serializable }))
    await step('interactive transaction rollback', async () => {
      try { await prisma.$transaction(async tx => { await tx.tag.create({ data: { name: 'itx-bad' } }); throw new Error('boom') }) } catch (e) { return { message: e.message, left: await prisma.tag.count({ where: { name: 'itx-bad' } }) } }
    })
    await step('interactive transaction snapshot (not allowed)', () => prisma.$transaction(async tx => tx.tag.count(), { isolationLevel: Prisma.TransactionIsolationLevel.Snapshot }))
    await step('$queryRaw tagged', () => prisma.$queryRaw`SELECT ${1} AS a, ${'two'} AS b, ${2.5} AS c, ${null} AS d, ${new Date('2020-01-01T00:00:00Z')} AS e, ${9007199254740993n} AS f, ${Buffer.from('ab', 'hex')} AS g`)
    await step('$queryRawUnsafe', () => prisma.$queryRawUnsafe('SELECT name FROM users WHERE id = @P1', 1))
    await step('$executeRaw', () => prisma.$executeRaw`UPDATE posts SET views = views + ${1} WHERE authorId = ${1}`)
    await step('$queryRaw error', () => prisma.$queryRaw`SELECT nope FROM users`)
    await step('delete cascade', async () => { await prisma.user.delete({ where: { email: 'ada@example.com' } }); return { posts: await prisma.post.count(), profiles: await prisma.profile.count() } })
    await step('deleteMany', () => prisma.tag.deleteMany({ where: { name: { startsWith: 'batch' } } }))
    await step('record not found P2025', () => prisma.user.update({ where: { email: 'nobody@example.com' }, data: { age: 1 } }))
  } finally {
    await prisma.$disconnect().catch(() => {})
  }
}
